version: '3.9'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/db-init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - '5432:5432'
    networks:
      - telegram-bot-net
    healthcheck:
      test: pg_isready -U postgres
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 30

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    networks:
      - telegram-bot-net
    healthcheck:
      test: redis-cli --raw incr ping
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 30

  grafana:
    image: grafana/grafana:9.0.0
    container_name: monitoring-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - telegram-bot-net
    mem_limit: '256m'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'

  promtail:
    image: grafana/promtail:2.5.0
    container_name: monitoring-promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./metrics/promtail.yaml:/etc/promtail/promtail.yaml
    command:
      - '-config.file=/etc/promtail/promtail.yaml'
    networks:
      - telegram-bot-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'

  loki:
    image: grafana/loki:2.5.0
    container_name: monitoring-loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    networks:
      - telegram-bot-net
    mem_limit: '256m'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'

  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: monitoring-prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - telegram-bot-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'

  bot:
    container_name: telegram-bot
    restart: unless-stopped
    platform: linux/amd64
    build: .
    environment:
      - TELEGRAM_BOT_WASTES_TELEGRAM_TOKEN=<token>
      - TELEGRAM_BOT_WASTES_DB_NAME=telegram_bot_wastes
      - TELEGRAM_BOT_WASTES_DB_HOST=postgres
      - TELEGRAM_BOT_WASTES_DB_PORT=5432
      - TELEGRAM_BOT_WASTES_DB_USER=postgres
      - TELEGRAM_BOT_WASTES_DB_PASSWORD=postgres
      - TELEGRAM_BOT_WASTES_REDIS_HOST=redis
      - TELEGRAM_BOT_WASTES_REDIS_PORT=6379
      - TELEGRAM_BOT_WASTES_REDIS_PASSWORD=redis
    networks:
      - telegram-bot-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        tag: '{{.ImageName}}'

volumes:
  postgres-data:
  redis-data:

networks:
  telegram-bot-net:
