CREATE DATABASE "telegram_bot_wastes";

\c "telegram_bot_wastes";

CREATE TABLE IF NOT EXISTS "users" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "user_name" character varying NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "wastes" (
    "id" uuid NOT NULL,
    "name" character varying NOT NULL,
    "cost" bigint NOT NULL,
    "category" character varying NOT NULL,
    "date" timestamptz NOT NULL,
    "user_wastes" bigint NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "wastes_users_wastes" FOREIGN KEY ("user_wastes") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "user_id" ON "users" ("id");

CREATE INDEX IF NOT EXISTS "waste_category" ON "wastes" ("category");

